/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * domain theme
 */
export interface Theme {
  /**
   * Domain ID
   */
  id?: number;
  /**
   * main color for accenting buttons etc
   */
  mainColor?: string;
  /**
   * secondary color for accenting titles etc
   */
  accentColor?: string;
  /**
   * should we use the dark mode?
   */
  dark?: boolean;
  /**
   * url to an image to use for the application background
   */
  backgroundImage?: string;
  /**
   * background positioning within the application frame
   */
  backgroundPosition?: "top" | "bottom" | "left" | "right" | "middle";
  /**
   * make the cards translucent in the main application
   */
  translucentCards?: boolean;
  /**
   * the name of a Google Web font which we will load for the UI
   */
  font?: string;
  /**
   * size of title text
   */
  titleSize?: number;
}
